// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfDWsnyIbnWOb_qFZnS6O-6JeSS02FLPw',
    appId: '1:257454421788:web:2e20146146beec2717ecd9',
    messagingSenderId: '257454421788',
    projectId: 'zzekakproject',
    authDomain: 'zzekakproject.firebaseapp.com',
    storageBucket: 'zzekakproject.appspot.com',
    measurementId: 'G-LQFW9MPZPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_6Y4VPZK6LFeYnJuFYh4CkxI1Bac33aM',
    appId: '1:257454421788:android:48af4cfe2b4d86b317ecd9',
    messagingSenderId: '257454421788',
    projectId: 'zzekakproject',
    storageBucket: 'zzekakproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGa6QCVDkVW3A4IgTiD_5eHaFGGU_Uek',
    appId: '1:257454421788:ios:7de484a8976808a917ecd9',
    messagingSenderId: '257454421788',
    projectId: 'zzekakproject',
    storageBucket: 'zzekakproject.appspot.com',
    iosBundleId: 'dev.com.zzeakak.app',
  );
}
