// Mocks generated by Mockito 5.4.4 from annotations
// in data/test/@mock/http_client/mock_httpcient_generator.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:data/io/http_client.dart' as _i2;
import 'package:data/io/json_serializable.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  @override
  _i3.Future<_i2.HTTPResponse> get<
              RequestBody extends _i4.ZzekakJsonSerializable>(
          _i2.HTTPRequest<RequestBody>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [request],
        ),
        returnValue:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #get,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #get,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.HTTPResponse>);

  @override
  _i3.Future<_i2.HTTPResponse> post<
              RequestBody extends _i4.ZzekakJsonSerializable>(
          _i2.HTTPRequest<RequestBody>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [request],
        ),
        returnValue:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #post,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #post,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.HTTPResponse>);

  @override
  _i3.Future<_i2.HTTPResponse> put<
              RequestBody extends _i4.ZzekakJsonSerializable>(
          _i2.HTTPRequest<RequestBody>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [request],
        ),
        returnValue:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #put,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #put,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.HTTPResponse>);

  @override
  _i3.Future<_i2.HTTPResponse> delete<
              RequestBody extends _i4.ZzekakJsonSerializable>(
          _i2.HTTPRequest<RequestBody>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [request],
        ),
        returnValue:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #delete,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.HTTPResponse>.value(_i5.dummyValue<_i2.HTTPResponse>(
          this,
          Invocation.method(
            #delete,
            [request],
          ),
        )),
      ) as _i3.Future<_i2.HTTPResponse>);
}
